name: Production Deploy

on:
  # Triggers the workflow on push or pull request events but only for the website branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Posts to the production endpoint to trigger a build of the public site
    steps:
      - name: Post to Netlify
        run: curl -X POST -d {} ${{ secrets.PRODUCTION_ENDPOINT }}
